name: miniproject
description: A hospital management system
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.9.0

dev_dependencies:
  test: ^1.25.2
  lints: ^3.0.0
